include:
- project: utilities/nt-dev
  file: nt_dev/release/gitlab-python-tests-basic.yml

.common__tests:
  script:
  - ntest --doctest-modules --coverage --exitfirst

test-mypy:
  extends: .common__tests_frozen
  script:
  - nt-mypy .

test-mypy-strict:
  extends: .common__tests_frozen
  script:
    - mypy --strict . || exit 1
  allow_failure:
    exit_codes: 1
